[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

# European timezones (CET/CEST)
[functions.autoposter]
  # Morning (9:07 AM CET)
  schedule = "07 9 * * *"

[functions.autoposter-noon]     
  # Noon (1:37 PM CET)
  schedule = "37 13 * * *"

[functions.autoposter-evening]  
  # Evening (6:27 PM CET)
  schedule = "27 18 * * *"

[functions.autoposter-latam-evening]
  # LATAM evening (11:17 PM CET / 6:17 PM LATAM)
  schedule = "17 23 * * *"

[functions.autoposter-latam-night]
  # LATAM night (1:07 AM CET / 8:07 PM LATAM)
  schedule = "07 1 * * *"