[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  schedule = "45-59/5 8, 0-15/5 9, 27-57/5 13, 0-45/5 18, 0-30/5 23, 0-30/5 1 * * *"